# Site settings
title: Gaeng Blog             # title of your website
SEOTitle: Gaeng Blog          # check out docs for more detail
description: "Programming Blog"    # ...

# SNS settings      
github_username: JIKYUNGHEE     # modify this account to yours

# Build settings
paginate: 10                # nums of posts in one page
